# Generated by Django 4.2.7 on 2023-11-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_delete_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum pulvinar ac ex vulputate venenatis. Vivamus sagittis turpis mollis ante sagittis, sagittis efficitur ligula cursus. Nulla pulvinar libero ut orci consectetur, a eleifend mi eleifend. Aliquam erat volutpat. Phasellus scelerisque est rutrum, interdum libero vel, dignissim tortor. Praesent suscipit eu massa ac fringilla. Proin hendrerit, sem vitae egestas fermentum, velit odio cursus lacus, a mollis lorem erat in elit. In eget quam libero. Donec sit amet placerat ipsum. In arcu eros, commodo id purus tristique, fermentum rutrum sem.'),
        ),
    ]
